<?php

namespace backend\modules\catalog\controllers\api;

/**
* This is the class for REST controller "RoomController".
*/

use common\models\Room;
use yii\helpers\ArrayHelper;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;

class RoomController extends ActiveController
{
public $modelClass = 'common\models\Room';

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'],
              $actions['create'],
              $actions['update'],
              $actions['delete']);

        return $actions;
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Room::find(),
            'pagination' => [
                'pageSize' => 1,
            ],
        ]);
        return $dataProvider;

    }

    public function actionCreate()
    {
        $model = new Room();

        if ($model->load(\Yii::$app->getRequest()->getBodyParams(), '')) {
            $model->save();
            return $model;
        } else {
            return $model->errors;
        }
    }

    public function actionUpdate($id)
    {
        $model = Room::findOne($id);

        if ($model->load(\Yii::$app->getRequest()->getBodyParams(), '')) {
            $model->save();
            return $model;
        } else {
            return $model->errors;
        }
    }

    public function behaviors()
     {
         $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub

         // add CORS filter
         $behaviors['corsFilter'] = [
             'class' => \yii\filters\Cors::class,
         ];
         return $behaviors;
     }
}
